### ISSUE TITLE
Add some new techniques for finding whether a number is even or odd

### ISSUE THREAD

**Issue by niyoj** [niyoj/even_odd_number#7]
## What is the issue?
This repository is the collection of several ways to solve a simple problem i.e. finding whether the given number is even or odd. In this Hacktoberfest 2021, you can start your open source journey by updating many more ways to solve this problem in many more languages and complete the 4 PR challenge to win a limited edition Hacktoberfest 2021 T-shirt. 👕 👕 

## What can be done?
- First, read the [`README.md`](https://github.com/niyoj/even_odd_number/README.md) very carefully and fork this repo.
- Then chose the programming language you want to use to solve the problem.
- Find whether the directory/folder for the programming language has been already created or not. For example: if you want to code in `python`, find a folder named `python` in the repo. 
- If the folder does not exist, you are free to create a new folder with the name of the programming language you want to code in,
- Solve this easy problem in different ways or in different languages. Submit a PR.
- And Horray! 🎉 🎉 ,  you have got +1 PR for Hacktoberfest. All the best for other PRs.

If you love this repo you can star it too. 😄
Feel free to drop your comment if you have any doubts.

**Please note** that for getting your PR accepted following conditions must be met;
- Your solution should be unique from other existing solutions. But two solutions can be the same if they are written in different programming langauges.
- Your PR must not be just something with your name added in the file or similar to something like that.

**Comment by AnirbanBall** [comment]
Can I contribute in this ? I m interested

**Comment by niyoj** [comment]
@AnirbanBall Yeah sure. Everyone can contribute in this repo. If you faced any problem feel free to comment here. Or you can connect me via [LinkedIn](https://www.linkedin.com/in/niyoj) too.

**Comment by AnirbanBall** [comment]
Great but I guess  pull request done  tomorrow will be considered .

**Comment by ajratnam** [comment]
I would also like to partake in this, in python using a different approach.

Also shall I write a small CLI script for python which countians a few tests to check the validity of the program, or is that not recommended for this project?

**Comment by niyoj** [comment]
@ajratnam You are welcome to contribute. Regarding the CLI script, it would be a great feature too.

**Comment by ajratnam** [comment]
Thanks!! I will be working on this soon.

**Comment by shouryagupta21** [comment]
please assign me this

**Comment by niyoj** [comment]
@shouryagupta21 You can submit a PR. And if PR is valid i.e. if you were able to show a new way of solving the problem your PR would be merged.
